// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPipecatApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPipecatApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPipecatApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPipecatApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPipecatApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPipecatApi(lhsKey, rhsKey) {
          if deepEqualsPipecatApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPipecatApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPipecatApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPipecatApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPipecatApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPipecatApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPipecatApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPipecatApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Maps to ai.pipecat.client.types.TransportState on Android / iOS.
enum PipecatTransportState: Int {
  case idle = 0
  case initializing = 1
  case initialized = 2
  case authenticating = 3
  case connecting = 4
  case connected = 5
  case ready = 6
  case disconnecting = 7
  case disconnected = 8
  case error = 9
}

/// Discriminator for [PipecatEventData]. Each value corresponds to a
/// PipecatEventCallbacks method on the native SDK.
enum PipecatEventType: Int {
  /// onUserTranscript — Whisper STT via TranscriptionFrame
  case userTranscript = 0
  /// onBotTranscript — final bot reply text
  case botTranscript = 1
  /// onBotLLMText — streaming LLM token chunks (LLMTextFrame)
  case botLlmText = 2
  /// onBotLLMStarted — LLMFullResponseStartFrame
  case botLlmStarted = 3
  /// onBotLLMStopped — LLMFullResponseEndFrame
  case botLlmStopped = 4
  /// onBotTTSStarted — TTSStartedFrame
  case botTtsStarted = 5
  /// onBotTTSStopped — TTSStoppedFrame
  case botTtsStopped = 6
  /// onBotStartedSpeaking — audio playback began
  case botStartedSpeaking = 7
  /// onBotStoppedSpeaking — audio playback ended
  case botStoppedSpeaking = 8
  /// onUserStartedSpeaking — Silero VAD rising edge
  case userStartedSpeaking = 9
  /// onUserStoppedSpeaking — Silero VAD falling edge
  case userStoppedSpeaking = 10
  /// onBotReady — pipeline fully initialized
  case botReady = 11
  /// onBotConnected
  case botConnected = 12
  /// onBotDisconnected
  case botDisconnected = 13
  /// onConnected — transport layer connected
  case transportConnected = 14
  /// onDisconnected — transport layer disconnected
  case transportDisconnected = 15
  /// onTransportStateChanged — generic state transition
  case transportStateChanged = 16
  /// onBackendError — ErrorFrame from pipeline
  case backendError = 17
}

/// Parameters required to start a Pipecat session.
///
/// [baseUrl] is the voice server origin (e.g. `https://voicebanking.example.com`).
/// The Pipecat SmallWebRTC transport calls `POST {baseUrl}/start`, then negotiates
/// SDP at `{baseUrl}/sessions/{sessionId}/api/offer` (handled inside the native SDK).
/// [customBodyJson] is a JSON-encoded string for extra parameters (avoids
/// Pigeon limitations with nested Object maps).
///
/// Generated class from Pigeon that represents data sent in messages.
struct SessionConfig: Hashable {
  /// Voice / SmallWebRTC server origin (scheme + host, no trailing slash).
  var baseUrl: String
  var enableMic: Bool
  var enableCam: Bool
  /// JSON-encoded Map<String,dynamic> of extra session parameters.
  /// Passed as `request_data` where supported by the transport.
  var customBodyJson: String? = nil
  /// JSON object of HTTP header names to values, e.g. `{"Authorization":"Bearer …"}`.
  /// Sent on `/start` and offer POSTs when supported by the native transport.
  var requestHeadersJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionConfig? {
    let baseUrl = pigeonVar_list[0] as! String
    let enableMic = pigeonVar_list[1] as! Bool
    let enableCam = pigeonVar_list[2] as! Bool
    let customBodyJson: String? = nilOrValue(pigeonVar_list[3])
    let requestHeadersJson: String? = nilOrValue(pigeonVar_list[4])

    return SessionConfig(
      baseUrl: baseUrl,
      enableMic: enableMic,
      enableCam: enableCam,
      customBodyJson: customBodyJson,
      requestHeadersJson: requestHeadersJson
    )
  }
  func toList() -> [Any?] {
    return [
      baseUrl,
      enableMic,
      enableCam,
      customBodyJson,
      requestHeadersJson,
    ]
  }
  static func == (lhs: SessionConfig, rhs: SessionConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPipecatApi(lhs.baseUrl, rhs.baseUrl) && deepEqualsPipecatApi(lhs.enableMic, rhs.enableMic) && deepEqualsPipecatApi(lhs.enableCam, rhs.enableCam) && deepEqualsPipecatApi(lhs.customBodyJson, rhs.customBodyJson) && deepEqualsPipecatApi(lhs.requestHeadersJson, rhs.requestHeadersJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SessionConfig")
    deepHashPipecatApi(value: baseUrl, hasher: &hasher)
    deepHashPipecatApi(value: enableMic, hasher: &hasher)
    deepHashPipecatApi(value: enableCam, hasher: &hasher)
    deepHashPipecatApi(value: customBodyJson, hasher: &hasher)
    deepHashPipecatApi(value: requestHeadersJson, hasher: &hasher)
  }
}

/// Flat, Pigeon-safe event envelope streamed from native → Flutter.
///
/// The [type] discriminator determines which nullable fields are populated.
/// Flutter-side [PipecatEvent] sealed classes provide a type-safe façade.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PipecatEventData: Hashable {
  var type: PipecatEventType
  /// Transcript text (user or bot) / LLM chunk text.
  var text: String? = nil
  /// True when the transcript is finalized (not interim).
  var isFinal: Bool? = nil
  /// Participant / user ID for the transcript source.
  var userId: String? = nil
  /// Detected language code (e.g. "en", "hi") from LanguageAnnotator.
  var language: String? = nil
  /// ISO-8601 timestamp of the transcription.
  var timestamp: String? = nil
  /// Populated only for [PipecatEventType.transportStateChanged].
  var transportState: PipecatTransportState? = nil
  /// Populated only for [PipecatEventType.backendError].
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipecatEventData? {
    let type = pigeonVar_list[0] as! PipecatEventType
    let text: String? = nilOrValue(pigeonVar_list[1])
    let isFinal: Bool? = nilOrValue(pigeonVar_list[2])
    let userId: String? = nilOrValue(pigeonVar_list[3])
    let language: String? = nilOrValue(pigeonVar_list[4])
    let timestamp: String? = nilOrValue(pigeonVar_list[5])
    let transportState: PipecatTransportState? = nilOrValue(pigeonVar_list[6])
    let errorMessage: String? = nilOrValue(pigeonVar_list[7])

    return PipecatEventData(
      type: type,
      text: text,
      isFinal: isFinal,
      userId: userId,
      language: language,
      timestamp: timestamp,
      transportState: transportState,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      text,
      isFinal,
      userId,
      language,
      timestamp,
      transportState,
      errorMessage,
    ]
  }
  static func == (lhs: PipecatEventData, rhs: PipecatEventData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPipecatApi(lhs.type, rhs.type) && deepEqualsPipecatApi(lhs.text, rhs.text) && deepEqualsPipecatApi(lhs.isFinal, rhs.isFinal) && deepEqualsPipecatApi(lhs.userId, rhs.userId) && deepEqualsPipecatApi(lhs.language, rhs.language) && deepEqualsPipecatApi(lhs.timestamp, rhs.timestamp) && deepEqualsPipecatApi(lhs.transportState, rhs.transportState) && deepEqualsPipecatApi(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PipecatEventData")
    deepHashPipecatApi(value: type, hasher: &hasher)
    deepHashPipecatApi(value: text, hasher: &hasher)
    deepHashPipecatApi(value: isFinal, hasher: &hasher)
    deepHashPipecatApi(value: userId, hasher: &hasher)
    deepHashPipecatApi(value: language, hasher: &hasher)
    deepHashPipecatApi(value: timestamp, hasher: &hasher)
    deepHashPipecatApi(value: transportState, hasher: &hasher)
    deepHashPipecatApi(value: errorMessage, hasher: &hasher)
  }
}

private class PipecatApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PipecatTransportState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PipecatEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return SessionConfig.fromList(self.readValue() as! [Any?])
    case 132:
      return PipecatEventData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PipecatApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PipecatTransportState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PipecatEventType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? SessionConfig {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PipecatEventData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PipecatApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PipecatApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PipecatApiPigeonCodecWriter(data: data)
  }
}

class PipecatApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PipecatApiPigeonCodec(readerWriter: PipecatApiPigeonCodecReaderWriter())
}

var pipecatApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: PipecatApiPigeonCodecReaderWriter());


/// Commands sent from Flutter to the native Pipecat SDK.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PipecatHostApi {
  /// Instantiate the native PipecatClient with the given session config.
  /// Must be called before [start]. Runs SDK init on a background thread.
  func initialize(config: SessionConfig, completion: @escaping (Result<Void, Error>) -> Void)
  /// Initiate SmallWebRTC SDP handshake; bot spawns on connection.
  func start(completion: @escaping (Result<Void, Error>) -> Void)
  /// Disconnect and release the native client resources.
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  /// Send a typed RTVI action to the bot (future extensibility).
  /// [dataJson] is a JSON-encoded payload to avoid Pigeon Object limitations.
  func sendAction(actionType: String, dataJson: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle microphone on/off without tearing down the session.
  func enableMic(enable: Bool) throws
  /// Toggle camera on/off (unused for voice-only, provided for completeness).
  func enableCam(enable: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PipecatHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PipecatApiPigeonCodec.shared }
  /// Sets up an instance of `PipecatHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PipecatHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Instantiate the native PipecatClient with the given session config.
    /// Must be called before [start]. Runs SDK init on a background thread.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! SessionConfig
        api.initialize(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Initiate SmallWebRTC SDP handshake; bot spawns on connection.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        api.start { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Disconnect and release the native client resources.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Send a typed RTVI action to the bot (future extensibility).
    /// [dataJson] is a JSON-encoded payload to avoid Pigeon Object limitations.
    let sendActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.sendAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let actionTypeArg = args[0] as! String
        let dataJsonArg = args[1] as! String
        api.sendAction(actionType: actionTypeArg, dataJson: dataJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendActionChannel.setMessageHandler(nil)
    }
    /// Toggle microphone on/off without tearing down the session.
    let enableMicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.enableMic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableMicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enableArg = args[0] as! Bool
        do {
          try api.enableMic(enable: enableArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enableMicChannel.setMessageHandler(nil)
    }
    /// Toggle camera on/off (unused for voice-only, provided for completeness).
    let enableCamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.enableCam\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableCamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enableArg = args[0] as! Bool
        do {
          try api.enableCam(enable: enableArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enableCamChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Type-safe EventChannel delivering [PipecatEventData] from native SDK
/// callbacks to Flutter. Pigeon generates `Stream<PipecatEventData>` on
/// the Dart side and a StreamHandler interface on the native side.
class StreamEventsStreamHandler: PigeonEventChannelWrapper<PipecatEventData> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.voice_banking_mobile.PipecatEventChannelApi.streamEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PipecatEventData>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
