// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.voice_banking_mobile

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PipecatApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Maps to ai.pipecat.client.types.TransportState on Android / iOS. */
enum class PipecatTransportState(val raw: Int) {
  IDLE(0),
  INITIALIZING(1),
  INITIALIZED(2),
  AUTHENTICATING(3),
  CONNECTING(4),
  CONNECTED(5),
  READY(6),
  DISCONNECTING(7),
  DISCONNECTED(8),
  ERROR(9);

  companion object {
    fun ofRaw(raw: Int): PipecatTransportState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Discriminator for [PipecatEventData]. Each value corresponds to a
 * PipecatEventCallbacks method on the native SDK.
 */
enum class PipecatEventType(val raw: Int) {
  /** onUserTranscript — Whisper STT via TranscriptionFrame */
  USER_TRANSCRIPT(0),
  /** onBotTranscript — final bot reply text */
  BOT_TRANSCRIPT(1),
  /** onBotLLMText — streaming LLM token chunks (LLMTextFrame) */
  BOT_LLM_TEXT(2),
  /** onBotLLMStarted — LLMFullResponseStartFrame */
  BOT_LLM_STARTED(3),
  /** onBotLLMStopped — LLMFullResponseEndFrame */
  BOT_LLM_STOPPED(4),
  /** onBotTTSStarted — TTSStartedFrame */
  BOT_TTS_STARTED(5),
  /** onBotTTSStopped — TTSStoppedFrame */
  BOT_TTS_STOPPED(6),
  /** onBotStartedSpeaking — audio playback began */
  BOT_STARTED_SPEAKING(7),
  /** onBotStoppedSpeaking — audio playback ended */
  BOT_STOPPED_SPEAKING(8),
  /** onUserStartedSpeaking — Silero VAD rising edge */
  USER_STARTED_SPEAKING(9),
  /** onUserStoppedSpeaking — Silero VAD falling edge */
  USER_STOPPED_SPEAKING(10),
  /** onBotReady — pipeline fully initialized */
  BOT_READY(11),
  /** onBotConnected */
  BOT_CONNECTED(12),
  /** onBotDisconnected */
  BOT_DISCONNECTED(13),
  /** onConnected — transport layer connected */
  TRANSPORT_CONNECTED(14),
  /** onDisconnected — transport layer disconnected */
  TRANSPORT_DISCONNECTED(15),
  /** onTransportStateChanged — generic state transition */
  TRANSPORT_STATE_CHANGED(16),
  /** onBackendError — ErrorFrame from pipeline */
  BACKEND_ERROR(17);

  companion object {
    fun ofRaw(raw: Int): PipecatEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Parameters required to start a Pipecat session.
 *
 * [baseUrl] is the voice server origin (e.g. `https://voicebanking.example.com`).
 * The Pipecat SmallWebRTC transport calls `POST {baseUrl}/start`, then negotiates
 * SDP at `{baseUrl}/sessions/{sessionId}/api/offer` (handled inside the native SDK).
 * [customBodyJson] is a JSON-encoded string for extra parameters (avoids
 * Pigeon limitations with nested Object maps).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SessionConfig (
  /** Voice / SmallWebRTC server origin (scheme + host, no trailing slash). */
  val baseUrl: String,
  val enableMic: Boolean,
  val enableCam: Boolean,
  /**
   * JSON-encoded Map<String,dynamic> of extra session parameters.
   * Passed as `request_data` where supported by the transport.
   */
  val customBodyJson: String? = null,
  /**
   * JSON object of HTTP header names to values, e.g. `{"Authorization":"Bearer …"}`.
   * Sent on `/start` and offer POSTs when supported by the native transport.
   */
  val requestHeadersJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionConfig {
      val baseUrl = pigeonVar_list[0] as String
      val enableMic = pigeonVar_list[1] as Boolean
      val enableCam = pigeonVar_list[2] as Boolean
      val customBodyJson = pigeonVar_list[3] as String?
      val requestHeadersJson = pigeonVar_list[4] as String?
      return SessionConfig(baseUrl, enableMic, enableCam, customBodyJson, requestHeadersJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      baseUrl,
      enableMic,
      enableCam,
      customBodyJson,
      requestHeadersJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SessionConfig
    return PipecatApiPigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && PipecatApiPigeonUtils.deepEquals(this.enableMic, other.enableMic) && PipecatApiPigeonUtils.deepEquals(this.enableCam, other.enableCam) && PipecatApiPigeonUtils.deepEquals(this.customBodyJson, other.customBodyJson) && PipecatApiPigeonUtils.deepEquals(this.requestHeadersJson, other.requestHeadersJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.enableMic)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.enableCam)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.customBodyJson)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.requestHeadersJson)
    return result
  }
}

/**
 * Flat, Pigeon-safe event envelope streamed from native → Flutter.
 *
 * The [type] discriminator determines which nullable fields are populated.
 * Flutter-side [PipecatEvent] sealed classes provide a type-safe façade.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PipecatEventData (
  val type: PipecatEventType,
  /** Transcript text (user or bot) / LLM chunk text. */
  val text: String? = null,
  /** True when the transcript is finalized (not interim). */
  val isFinal: Boolean? = null,
  /** Participant / user ID for the transcript source. */
  val userId: String? = null,
  /** Detected language code (e.g. "en", "hi") from LanguageAnnotator. */
  val language: String? = null,
  /** ISO-8601 timestamp of the transcription. */
  val timestamp: String? = null,
  /** Populated only for [PipecatEventType.transportStateChanged]. */
  val transportState: PipecatTransportState? = null,
  /** Populated only for [PipecatEventType.backendError]. */
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PipecatEventData {
      val type = pigeonVar_list[0] as PipecatEventType
      val text = pigeonVar_list[1] as String?
      val isFinal = pigeonVar_list[2] as Boolean?
      val userId = pigeonVar_list[3] as String?
      val language = pigeonVar_list[4] as String?
      val timestamp = pigeonVar_list[5] as String?
      val transportState = pigeonVar_list[6] as PipecatTransportState?
      val errorMessage = pigeonVar_list[7] as String?
      return PipecatEventData(type, text, isFinal, userId, language, timestamp, transportState, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      text,
      isFinal,
      userId,
      language,
      timestamp,
      transportState,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PipecatEventData
    return PipecatApiPigeonUtils.deepEquals(this.type, other.type) && PipecatApiPigeonUtils.deepEquals(this.text, other.text) && PipecatApiPigeonUtils.deepEquals(this.isFinal, other.isFinal) && PipecatApiPigeonUtils.deepEquals(this.userId, other.userId) && PipecatApiPigeonUtils.deepEquals(this.language, other.language) && PipecatApiPigeonUtils.deepEquals(this.timestamp, other.timestamp) && PipecatApiPigeonUtils.deepEquals(this.transportState, other.transportState) && PipecatApiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.type)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.text)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.isFinal)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.userId)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.language)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.timestamp)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.transportState)
    result = 31 * result + PipecatApiPigeonUtils.deepHash(this.errorMessage)
    return result
  }
}
private open class PipecatApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PipecatTransportState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PipecatEventType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionConfig.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PipecatEventData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PipecatTransportState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PipecatEventType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SessionConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PipecatEventData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val PipecatApiPigeonMethodCodec = StandardMethodCodec(PipecatApiPigeonCodec())


/**
 * Commands sent from Flutter to the native Pipecat SDK.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PipecatHostApi {
  /**
   * Instantiate the native PipecatClient with the given session config.
   * Must be called before [start]. Runs SDK init on a background thread.
   */
  fun initialize(config: SessionConfig, callback: (Result<Unit>) -> Unit)
  /** Initiate SmallWebRTC SDP handshake; bot spawns on connection. */
  fun start(callback: (Result<Unit>) -> Unit)
  /** Disconnect and release the native client resources. */
  fun stop(callback: (Result<Unit>) -> Unit)
  /**
   * Send a typed RTVI action to the bot (future extensibility).
   * [dataJson] is a JSON-encoded payload to avoid Pigeon Object limitations.
   */
  fun sendAction(actionType: String, dataJson: String, callback: (Result<Unit>) -> Unit)
  /** Toggle microphone on/off without tearing down the session. */
  fun enableMic(enable: Boolean)
  /** Toggle camera on/off (unused for voice-only, provided for completeness). */
  fun enableCam(enable: Boolean)

  companion object {
    /** The codec used by PipecatHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PipecatApiPigeonCodec()
    }
    /** Sets up an instance of `PipecatHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PipecatHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as SessionConfig
            api.initialize(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.start{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stop{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.sendAction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val actionTypeArg = args[0] as String
            val dataJsonArg = args[1] as String
            api.sendAction(actionTypeArg, dataJsonArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.enableMic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enableArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.enableMic(enableArg)
              listOf(null)
            } catch (exception: Throwable) {
              PipecatApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voice_banking_mobile.PipecatHostApi.enableCam$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enableArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.enableCam(enableArg)
              listOf(null)
            } catch (exception: Throwable) {
              PipecatApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PipecatApiPigeonStreamHandler<T>(
    val wrapper: PipecatApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PipecatApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * Type-safe EventChannel delivering [PipecatEventData] from native SDK
 * callbacks to Flutter. Pigeon generates `Stream<PipecatEventData>` on
 * the Dart side and a StreamHandler interface on the native side.
 */
abstract class StreamEventsStreamHandler : PipecatApiPigeonEventChannelWrapper<PipecatEventData> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.voice_banking_mobile.PipecatEventChannelApi.streamEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PipecatApiPigeonStreamHandler<PipecatEventData>(streamHandler)
      EventChannel(messenger, channelName, PipecatApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PipecatApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PipecatEventData>) {}

override fun onCancel(p0: Any?) {}
}
      
